# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "debian12"
  config.vm.box = "generic/debian12"
  config.vm.network "private_network", ip: "192.168.56.42"

  config.vm.provision :shell, :path => "./scripts/bootstrap.sh"
  config.vm.provision "file", source: "repo/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb", destination: "/tmp/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb"
  config.vm.provision :shell, privileged: false, :path => "./scripts/ruby.sh"
  config.vm.provision :shell, :path => "./scripts/node.sh"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.memory = 3072
    virtualbox.cpus = 2
  end
end
