# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "desktop8"
  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "192.168.45.41"

  config.vm.provision :shell, :path => "./scripts/bootstrap.sh"
  config.vm.provision :shell, privileged: false, :path => "./scripts/rbenv.sh"
  config.vm.provision :shell, :path => "./scripts/node.sh"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

end
