# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "fedora36"
  config.vm.box = "generic-x64/fedora36"
  config.vm.network "private_network", ip: "192.168.56.30"

  config.vm.provision "file", source: "repo/fullstaq.repo", destination: "/tmp/fullstaq.repo"
  config.vm.provision "shell", inline: "cp /tmp/fullstaq.repo /etc/yum.repos.d/"
  config.vm.provision "file", source: "scripts/rbenv.sh", destination: "/tmp/rbenv.sh"
  config.vm.provision "shell", inline: "cp /tmp/rbenv.sh /etc/profile.d/"
  config.vm.provision :shell, privileged: false, :path => "./scripts/ruby.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
