# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "server1804"
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.40"

  config.vm.provision :shell, :path => "./scripts/bootstrap.sh"
  config.vm.provision :shell, privileged: false, :path => "./scripts/rbenv.sh"
  config.vm.provision :shell, :path => "./scripts/node.sh"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
end
