# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "amazonlinux2023"
  config.vm.box = "gbailey/al2023"
  config.vm.network "private_network", ip: "192.168.56.21"

  config.vm.provision "file", source: "repo/fullstaq.repo", destination: "/tmp/fullstaq.repo"
  config.vm.provision "file", source: "repo/epel.repo", destination: "/tmp/epel.repo"
  config.vm.provision "file", source: "repo/wkhtmltox-0.12.6.1-2.almalinux9.x86_64.rpm", destination: "/tmp/wkhtmltox-0.12.6.1-2.almalinux9.x86_64.rpm"
  config.vm.provision "shell", inline: "cp /tmp/*.repo /etc/yum.repos.d/"
  config.vm.provision :shell, privileged: false, :path => "./scripts/ruby.sh"
  config.vm.provision :shell, privileged: false, :path => "./scripts/node.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
