# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "amazonlinux2"
  config.vm.box = "gbailey/amzn2"
  config.vm.network "private_network", ip: "192.168.44.20"

#  config.vm.provision "file", source: "repo/fullstaq.repo", destination: "/tmp/fullstaq.repo"
#  config.vm.provision "shell", inline: "cp /tmp/fullstaq.repo /etc/yum.repos.d/"
#  config.vm.provision :shell, privileged: false, :path => "./scripts/ruby.sh"
  config.vm.provision :shell, privileged: false, :path => "./scripts/rbenv.sh"
  config.vm.provision :shell, :path => "./scripts/node.sh"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
